export const LOCAL_STORAGE_KEYS = {
  THEME: 'THEME',
  CLIENT_ID: 'CLIENT_ID',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  ACCESS_EXP: 'ACCESS_EXP',
  REFRESH_EXP: 'REFRESH_EXP',
}
